
from datetime import datetime

def generate_launch_timeline(plan_length=7, client_name="BrandVision User"):
    today = datetime.today().strftime('%B %d, %Y')

    days = [
        {"day": 1, "prompt": "Post your origin story – why you created this offer.", "cta": "Invite people to comment if they’ve ever struggled with this too."},
        {"day": 2, "prompt": "Drop a myth-busting post related to your niche.", "cta": "End with: 'Tag a friend who still believes this!'"},
        {"day": 3, "prompt": "Share a client result or transformation (or your own before/after).", "cta": "Encourage DMs: 'Want this result? Message me the word READY.'"},
        {"day": 4, "prompt": "Educate: teach 1 actionable tip that your audience can apply today.", "cta": "Use a call to save the post or share it to stories."},
        {"day": 5, "prompt": "Go behind the scenes – show your process or workspace.", "cta": "Ask: 'Want to see more of this?' and use a poll or story."},
        {"day": 6, "prompt": "Soft launch your offer: share 3 key benefits + who it’s for.", "cta": "Link to your booking page or drop your offer in stories."},
        {"day": 7, "prompt": "Post a bold opinion or truth that aligns with your brand values.", "cta": "Ask: 'Agree or disagree?' to spark engagement."}
    ]

    if plan_length == 14:
        days += [
            {"day": 8, "prompt": "Highlight your unique framework or how you get results.", "cta": "Use a carousel or slide-style post."},
            {"day": 9, "prompt": "List post: '5 things I wish I knew before I started...'", "cta": "End with: 'Which one hit hardest for you?'"},
            {"day": 10, "prompt": "FAQ post – answer 3 questions you’ve been asked.", "cta": "CTA: Drop your questions for me to answer next."},
            {"day": 11, "prompt": "Talk about a time you almost gave up.", "cta": "Invite vulnerability: 'What’s kept you going lately?'"},
            {"day": 12, "prompt": "Tell the story of your first sale or client.", "cta": "Ask: 'Want help landing your first sale too?'"},
            {"day": 13, "prompt": "Do a live or video talking about your mission.", "cta": "CTA: Invite them to join your email list or DM for replays."},
            {"day": 14, "prompt": "Show proof of momentum – screenshots, comments, testimonials.", "cta": "Finish strong with urgency: 'Spots are closing soon!' "}
        ]

    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Arial', sans-serif; margin: 40px; color: #222; }}
            h1 {{ font-size: 24px; }}
            h2 {{ font-size: 18px; margin-top: 30px; }}
            .day-block {{ margin-bottom: 20px; }}
            .footer {{ margin-top: 40px; font-size: 12px; color: #888; border-top: 1px solid #ccc; padding-top: 10px; }}
        </style>
    </head>
    <body>
        <h1>{client_name} – Your {plan_length}-Day AI Launch Plan</h1>
        <p><strong>Date:</strong> {today}</p>
    """

    for entry in days:
        html += f"""
        <div class="day-block">
            <h2>Day {entry['day']}</h2>
            <p><strong>Prompt:</strong> {entry['prompt']}</p>
            <p><strong>CTA:</strong> {entry['cta']}</p>
        </div>
        """

    html += f"""
        <div class="footer">
            Generated by BrandVision Profiler by CGL | www.brandvisionprofiler.com
        </div>
    </body>
    </html>
    """

    return html.strip()