services:
  - type: web
    name: brandvision-profiler
    env: python
    buildCommand: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:8000 brandvision_profiler_premium_final:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.18"
